apiVersion: v1
entries:
  azure-api-management-gateway:
  - apiVersion: v2
    appVersion: 2.0.3
    created: "2022-06-17T10:07:22.024742157+03:00"
    description: A Helm chart to deploy the self-hosted gateway of Azure API Management
      on Kubernetes
    digest: 8189ff206594c4dc56f77e95b7e563b868aa0f0d1f91630ddc21df4fc152aa05
    home: https://azure.microsoft.com/en-us/services/api-management/
    icon: https://github.com/Azure/API-Management/raw/main/media/apim-logo.png
    keywords:
    - Microsoft Azure
    - Azure
    - API Gateway
    - API Management
    - Cloud
    - Multi-Cloud
    - Hybrid
    - Kubernetes
    - Cloud-Native
    kubeVersion: '>=v1.17.0-0'
    maintainers:
    - name: Vlad Vinogradsky
      url: https://github.com/vladvino
    - name: Tom Kerkhove
      url: https://github.com/tomkerkhove
    name: azure-api-management-gateway
    sources:
    - https://github.com/Azure/api-management-self-hosted-gateway
    urls:
    - azure-api-management-gateway-1.1.0.tgz
    version: 1.1.0
  cert-manager:
  - annotations:
      artifacthub.io/prerelease: "false"
      artifacthub.io/signKey: |
        fingerprint: 1020CF3C033D4F35BAE1C19E1226061C665DF13E
        url: https://cert-manager.io/public-keys/cert-manager-keyring-2021-09-20-1020CF3C033D4F35BAE1C19E1226061C665DF13E.gpg
    apiVersion: v1
    appVersion: v1.8.1
    created: "2022-06-17T10:07:22.030573148+03:00"
    description: A Helm chart for cert-manager
    digest: b8d0dd5c95398db9308b649f7ef70ca3a0db1bb8859b43f9672c7f66871d0ef9
    home: https://github.com/cert-manager/cert-manager
    icon: https://raw.githubusercontent.com/cert-manager/cert-manager/master/logo/logo.png
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    maintainers:
    - email: cert-manager-maintainers@googlegroups.com
      name: cert-manager-maintainers
    name: cert-manager
    sources:
    - https://github.com/cert-manager/cert-manager
    urls:
    - cert-manager-v1.8.1.tgz
    version: v1.8.1
  echo-service:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-06-17T10:07:22.031710947+03:00"
    description: A Helm chart for Kubernetes
    digest: cf886a7daad4594a1ec3ebb1dc65d97b93e19cd1f494ce7bee4923293782eaba
    name: echo-service
    type: application
    urls:
    - echo-service-0.1.0.tgz
    version: 0.1.0
  kube-prometheus-stack:
  - annotations:
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/prometheus-community/helm-charts
        - name: Upstream Project
          url: https://github.com/prometheus-operator/kube-prometheus
      artifacthub.io/operator: "true"
    apiVersion: v2
    appVersion: 0.57.0
    created: "2022-06-17T10:07:22.060855242+03:00"
    dependencies:
    - condition: kubeStateMetrics.enabled
      name: kube-state-metrics
      repository: https://prometheus-community.github.io/helm-charts
      version: 4.9.*
    - condition: nodeExporter.enabled
      name: prometheus-node-exporter
      repository: https://prometheus-community.github.io/helm-charts
      version: 3.3.*
    - condition: grafana.enabled
      name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 6.29.*
    description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards,
      and Prometheus rules combined with documentation and scripts to provide easy
      to operate end-to-end Kubernetes cluster monitoring with Prometheus using the
      Prometheus Operator.
    digest: f71a4ab49082c1bcba06e83c0e1f3b9027fba00aca57d627a908901fd4ee954d
    home: https://github.com/prometheus-operator/kube-prometheus
    icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
    keywords:
    - operator
    - prometheus
    - kube-prometheus
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: andrew@quadcorps.co.uk
      name: andrewgkew
    - name: bismarck
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    - email: gianrubio@gmail.com
      name: gianrubio
    - email: github.gkarthiks@gmail.com
      name: gkarthiks
    - email: kube-prometheus-stack@sisti.pt
      name: GMartinez-Sisti
    - email: scott@r6by.com
      name: scottrigby
    - email: miroslav.hadzhiev@gmail.com
      name: Xtigyro
    name: kube-prometheus-stack
    sources:
    - https://github.com/prometheus-community/helm-charts
    - https://github.com/prometheus-operator/kube-prometheus
    type: application
    urls:
    - kube-prometheus-stack-36.0.1.tgz
    version: 36.0.1
  logging-operator:
  - apiVersion: v1
    appVersion: 3.17.7
    created: "2022-06-17T10:07:22.068201732+03:00"
    description: A Helm chart to install Banzai Cloud logging-operator
    digest: ccb74bcddbaeaaf051ac6e526e2dcbab4df682553ddcce8b6808dd50600c7e26
    name: logging-operator
    urls:
    - logging-operator-3.17.7.tgz
    version: 3.17.7
  logging-operator-logging:
  - apiVersion: v1
    appVersion: 3.17.7
    created: "2022-06-17T10:07:22.069343127+03:00"
    description: A Helm chart to configure logging resource for the Logging operator
    digest: 662667f6be3c33b66f8437594040a5f3ebe8723d8a43a21dd9a73096c5afe29e
    icon: https://raw.githubusercontent.com/banzaicloud/logging-operator/master/docs/img/icon.png
    name: logging-operator-logging
    urls:
    - logging-operator-logging-3.17.7.tgz
    version: 3.17.7
generated: "2022-06-17T10:07:22.022808021+03:00"
