apiVersion: v1
entries:
  echo-service:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-11-25T21:07:46.363949031+03:00"
    description: A Helm chart for Kubernetes
    digest: cf886a7daad4594a1ec3ebb1dc65d97b93e19cd1f494ce7bee4923293782eaba
    name: echo-service
    type: application
    urls:
    - https://emrahkk.github.io/helm/charts/echo-service-0.1.0.tgz
    version: 0.1.0
generated: "2021-11-25T21:07:46.36343146+03:00"
